from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class PathStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"


class NodeType(str, Enum):
    LEARNING = "LEARNING"
    PROJECT = "PROJECT"
    INTERVIEW = "INTERVIEW"


class NodeDifficulty(str, Enum):
    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"


class NodeStatus(str, Enum):
    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"
    COMPLETED = "COMPLETED"


class NodeDraft(BaseModel):
    """Represents a milestone node as generated by the LLM (no runtime server fields)."""

    title: str = Field(description="Title of the milestone node.")
    description: str = Field(description="Summary of what the candidate will do or learn.")
    type: NodeType = Field(description="Node type: LEARNING | PROJECT | INTERVIEW.")
    difficulty: NodeDifficulty = Field(description="Difficulty level: EASY | MEDIUM | HARD.")
    tags: list[str] = Field(default_factory=list, description="Keywords / skills covered.")


class CareerPathLLMOutput(BaseModel):
    """Validates the raw LLM career path generation payload."""

    title: str = Field(description="Title of the career path.")
    description: str = Field(description="High-level roadmap description.")
    tags: list[str] = Field(default_factory=list, description="Categorization tags.")
    missing_skills: list[str] = Field(
        default_factory=list, description="Skills targeted by this path."
    )
    nodes: list[NodeDraft] = Field(
        default_factory=list,
        description="Sequential milestone nodes composing the career path.",
    )


class CreatePathRequest(BaseModel):
    analysis_id: str = Field(description="ID of the READY analysis document.")
    rec_index: int = Field(
        ge=0,
        description="0-indexed position of the recommendation in analysis.recommendations.",
    )


class PathNode(BaseModel):
    step: int = Field(description="0-indexed sequence position of the node.")
    title: str = Field(description="Title of the node.")
    description: str = Field(description="Description of the node task or lesson.")
    type: NodeType = Field(description="Node type: LEARNING | PROJECT | INTERVIEW.")
    difficulty: NodeDifficulty = Field(description="Node difficulty: EASY | MEDIUM | HARD.")
    tags: list[str] = Field(default_factory=list, description="Tags associated with the node.")
    status: NodeStatus = Field(
        description="Node lifecycle status: LOCKED | UNLOCKED | COMPLETED."
    )
    is_expanded: bool = Field(
        default=False,
        description="True once look-ahead template generation has completed.",
    )
    linked_content_id: Optional[str] = Field(
        default=None,
        description="ID of the generated template document, or null if not yet expanded.",
    )
    linked_content_collection: Optional[str] = Field(
        default=None,
        description="Name of the template collection (learning_templates, project_templates, interview_templates).",
    )
    max_score: int = Field(default=0, description="Max attainable score for project/interview sessions.")
    attempts: int = Field(default=0, description="Number of failed/abandoned attempts.")
    xp_gained: int = Field(default=0, description="XP earned from completing this node.")
    completed_at: Optional[datetime] = Field(
        default=None, description="ISO8601 timestamp of node completion."
    )


class PathDetail(BaseModel):
    path_id: str = Field(description="ID of the career path document.")
    title: str = Field(description="Title of the career path.")
    description: str = Field(description="Roadmap description.")
    status: PathStatus = Field(description="Path status: ACTIVE | ARCHIVED | DELETED.")
    tags: list[str] = Field(default_factory=list, description="Categorization tags.")
    missing_skills: list[str] = Field(
        default_factory=list, description="Missing skills target list."
    )
    total_nodes: int = Field(description="Total number of nodes in the path.")
    completed_at: Optional[datetime] = Field(
        default=None, description="ISO8601 timestamp when the last node was completed."
    )
    created_at: datetime = Field(description="ISO8601 creation timestamp.")
    deleted_at: Optional[datetime] = Field(
        default=None, description="ISO8601 soft deletion timestamp."
    )
    analysis_id: str = Field(description="ID of the originating analysis.")
    recommendation_index: int = Field(
        description="Index of the recommendation from which this path was created."
    )
    nodes: list[PathNode] = Field(
        default_factory=list, description="Embedded sequential node list."
    )


class PathProgress(BaseModel):
    completed_nodes: int = Field(description="Number of nodes with COMPLETED status.")
    percentage: int = Field(description="Overall completion percentage (0 to 100).")


class PathSummary(BaseModel):
    path_id: str = Field(description="ID of the career path document.")
    title: str = Field(description="Title of the career path.")
    status: PathStatus = Field(description="Path status: ACTIVE | ARCHIVED | DELETED.")
    total_nodes: int = Field(description="Total number of nodes in the path.")
    completed_at: Optional[datetime] = Field(
        default=None, description="ISO8601 completion timestamp."
    )
    created_at: datetime = Field(description="ISO8601 creation timestamp.")
    deleted_at: Optional[datetime] = Field(
        default=None, description="ISO8601 soft deletion timestamp."
    )
    progress: PathProgress = Field(description="Dynamic progress summary.")


class PathList(BaseModel):
    paths: list[PathSummary] = Field(
        default_factory=list, description="List of matching career paths."
    )


class ArchiveResponse(BaseModel):
    message: str = "Career path archived successfully"
    path_id: str
    status: PathStatus = PathStatus.ARCHIVED


class DeleteResponse(BaseModel):
    message: str = "Career path deleted successfully"
    path_id: str
    status: PathStatus = PathStatus.DELETED
    deleted_at: datetime


class RestoreResponse(BaseModel):
    message: str = "Career path restored successfully"
    path_id: str
    status: PathStatus = PathStatus.ACTIVE
    deleted_at: Optional[datetime] = None
